name:        typed-process
version:     0.2.8.0
synopsis:    Run external processes, with strong typing of streams
description: Please see the tutorial at <https://github.com/fpco/typed-process#readme>
category:    System
author:      Michael Snoyman
maintainer:  michael@snoyman.com
license:     MIT
github:      fpco/typed-process
homepage:    https://github.com/fpco/typed-process

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4.12 && <5
- async >=2.0
- bytestring
- process >=1.2
- stm
- transformers
- unliftio-core

library:
  source-dirs: src
  when:
  - condition: os(windows)
    cpp-options: -DWINDOWS

tests:
  typed-process-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base64-bytestring
    - hspec
    - temporary
    - typed-process
  typed-process-test-single-threaded:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - base64-bytestring
    - hspec
    - temporary
    - typed-process
