name: Tests

on:
    pull_request:
    push:
    workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        resolver: [nightly, lts-21, lts-20, lts-19, lts-18, lts-17, lts-16, lts-15, lts-14]
        # lts-15 on windows-latest says
        #
        # Access violation in generated code when writing 0x0
        #
        # Attempting to reconstruct a stack trace...
        #
        #   Frame	Code address
        # * 0x461da80	0x37f7b66 C:\Users\runneradmin\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3\bin\ghc.exe+0x33f7b66
        # * 0x461da88	0x3277bb9 C:\Users\runneradmin\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3\bin\ghc.exe+0x2e77bb9
        # * 0x461da90	0x5
        # * 0x461da98	0x5
        # * 0x461daa0	0x3d7dc22 C:\Users\runneradmin\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3\bin\ghc.exe+0x397dc22
        # * 0x461daa8	0x65cc9b0
        exclude:
           - os: windows-latest
             resolver: lts-15
           # Seems like ghcup on macosx-aarch64 doesn't support the
           # GHCs needed for 14 to 17
           - os: macos-latest
             resolver: lts-14
           - os: macos-latest
             resolver: lts-15
           - os: macos-latest
             resolver: lts-16
           - os: macos-latest
             resolver: lts-17
           # Compilation fails on 18 and 19 with an LLVM version
           # problem
           - os: macos-latest
             resolver: lts-18
           - os: macos-latest
             resolver: lts-19

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      # This does not seem to cache on Windows, because ~/.stack does
      # not exist on Windows. I don't know how caching on Windows is
      # supposed to work.
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            curl -sSL https://get.haskellstack.org/ | sh -s - -f
            stack test --fast --no-terminal --resolver=${{ matrix.resolver }}
